Add-Type -AssemblyName System.Drawing
$bmp = New-Object System.Drawing.Bitmap(50, 50)
$g = [System.Drawing.Graphics]::FromImage($bmp)
$g.Clear([System.Drawing.Color]::Transparent)
$pen = New-Object System.Drawing.Pen([System.Drawing.ColorTranslator]::FromHtml('#0077bb'), 2)
$g.DrawLine($pen, 14, 12, 14, 28)
$g.DrawLine($pen, 14, 28, 26, 28)
$g.DrawLine($pen, 20, 18, 20, 34)
$g.DrawLine($pen, 20, 34, 32, 34)
$g.DrawLine($pen, 26, 24, 26, 40)
$g.DrawLine($pen, 26, 40, 38, 40)
$bmp.Save("d:\hoctap\NKS\qr-order\public\images\logo.png", [System.Drawing.Imaging.ImageFormat]::Png)
$g.Dispose()
$bmp.Dispose()
